Repository DigitalCareerInstitute/marketing-website, pull requests merged in 2018-11, with the labels that each got.

#79 Enhance story model is done
  controllers/admin/AdminStoriesController.js
  models/story.js
  package-lock.json
  package.json
  routes/admin/stories.js
  temp/.gitignore
  test/story-test.js
  views/admin/editCategory.pug
  views/admin/editLocation.pug
  views/admin/editPage.pug
  views/admin/editStory.pug
  views/admin/pages.pug
  views/admin/stories.pug
  views/layout.pug
  views/mixins/contactlist.pug
  views/mixins/pagelist.pug
  views/mixins/storyForm.pug
  views/mixins/storylist.pug
  views/story.pug
Labels: Backend

#86 Fix the issue inside the seeds file
  seeds.js
Labels: Backend

#96 Ignore content of /uploads/images folder
  controllers/admin/AdminEventsController.js
  package-lock.json
  uploads/.gitignore
Labels: Backend, bug, good first issue

#99 delete .gitignore from uploads folder
  uploads/images/.gitignore
Labels: bug

#122 Cashing data with redis
  .env.example
  helper.js
  package-lock.json
  package.json
  server.js
Labels: Backend

#126 Footer issue #117
  assets/css/footer.css
  assets/css/style.scss
  package-lock.json
  server.js
  uploads/example_image_1.jpg
  uploads/example_image_2.jpg
  uploads/example_image_3.jpg
  views/index.pug
  views/layout.pug
  views/mixins/courses/oneyear.pug
  views/mixins/landingpage/footer.pug
Labels: Frontend

#128 Clean up css structure - issue #120
  assets/css/contactform.css
  assets/css/jumbotron.css
  assets/css/ourCoursesSection.css
  assets/css/partners.css
  assets/css/quote.css
  assets/css/stats-counter.css
  assets/css/style.scss
  assets/css/testimonialsDevugees.css
  assets/css/upcomingEvents.css
  assets/css/video.css
  public/style.css
  public/style.css.map
  uploads/example_image_1.jpg
  uploads/example_image_2.jpg
  uploads/example_image_3.jpg
  views/index.pug
  views/layout.pug
Labels: Frontend

#127 Add a class for each view
  server.js
  views/layout.pug
Labels: Backend, Frontend

#133 Issue #109 and #110 | nav-bax-responsive and meta tag scaling
  assets/css/footer.css
  assets/css/style.scss
  public/style.css
  public/style.css.map
  views/layout.pug
  views/mixins/landingpage/getinvolved.pug
  views/mixins/navigation.pug
Labels: Frontend

#123 finished get Involved section
  assets/css/contact.scss
  assets/css/footer.scss
  assets/css/global.scss
  assets/css/header.scss
  assets/css/storylist.scss
  assets/css/style.scss
  public/style.bundle.js
  public/style.bundle.js.map
  public/style.css
  public/style.css.map
  views/mixins/landingpage/getinvolved.pug
Labels: Frontend

#143 issue #139 fixed. contact for is showed across the site
  routes/index.js
  views/mixins/courses/singleCourse.pug
  views/mixins/navigation.pug
Labels: Frontend
